/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface GameAchievements {
  achievement_name: string;
  achievement_type: string;
  completed_at: number | null;
  created_at: Generated<number | null>;
  description: string | null;
  game_id: number;
  id: Generated<number | null>;
  is_completed: Generated<number | null>;
}

export interface GameGallery {
  alt: string | null;
  created_at: Generated<number | null>;
  game_id: number;
  id: Generated<number | null>;
  image_path: string;
  image_type: string;
  relative_path: string;
}

export interface GameLinks {
  created_at: Generated<number | null>;
  description: string | null;
  game_id: number;
  icon: string | null;
  id: Generated<number | null>;
  title: string | null;
  updated_at: Generated<number | null>;
  url: string;
}

export interface GameLogs {
  ended_at: number | null;
  game_id: number;
  game_mode: Generated<string>;
  id: Generated<number | null>;
  launch_state: string;
  launched_at: number;
  play_time: number;
}

export interface Games {
  category: string | null;
  created_at: Generated<number | null>;
  disk_size: Generated<number | null>;
  game_name: string;
  game_version: Generated<string>;
  id: Generated<number | null>;
  last_launch_time: number | null;
  launch_count: Generated<number | null>;
  launch_path: string;
  total_play_time: Generated<number | null>;
  updated_at: Generated<number | null>;
}

export interface GameSaveBackups {
  backup_name: string;
  backup_path: string;
  created_at: Generated<number | null>;
  file_size: Generated<number | null>;
  game_id: number;
  id: Generated<number | null>;
}

export interface GameSavePaths {
  created_at: Generated<number | null>;
  file_size: Generated<number | null>;
  game_id: number;
  id: Generated<number | null>;
  save_path: string;
  updated_at: Generated<number | null>;
}

export interface GameVersions {
  created_at: Generated<number | null>;
  file_size: number | null;
  game_id: number;
  id: Generated<number | null>;
  summary: string | null;
  updated_at: Generated<number | null>;
  version: string;
}

export interface DB {
  game_achievements: GameAchievements;
  game_gallery: GameGallery;
  game_links: GameLinks;
  game_logs: GameLogs;
  game_save_backups: GameSaveBackups;
  game_save_paths: GameSavePaths;
  game_versions: GameVersions;
  games: Games;
}
